Repository firebase/extensions, pull requests merged in 2020-01, with the labels that each got.

#153 fix(storage-resize-images) relax bucket naming rules
  storage-resize-images/extension.yaml
Labels: cla: yes

#142 fix(storage-resize-images): Fix "TypeError: Cannot set property 'resizedImage' of undefined" by ensuring metadata is always available
  storage-resize-images/functions/lib/index.js
  storage-resize-images/functions/src/index.ts
Labels: cla: yes, in-progress

#134 fix(storage-resize-images): fix bug where name of resized file was missing original name if there was no file extension
  storage-resize-images/__tests__/extractFileNameWithoutExtension.ts
  storage-resize-images/functions/lib/index.js
  storage-resize-images/functions/lib/util.js
  storage-resize-images/functions/src/index.ts
  storage-resize-images/functions/src/util.ts
Labels: cla: yes, in-progress

#125 build(*): updated firebase-functions and firebase-admin dependencies
  auth-mailchimp-sync/package-lock.json
  auth-mailchimp-sync/package.json
  delete-user-data/package-lock.json
  delete-user-data/package.json
  exts-test-data/package-lock.json
  firestore-bigquery-export/package-lock.json
  firestore-bigquery-export/package.json
  firestore-send-email/package-lock.json
  firestore-shorten-urls-bitly/package-lock.json
  firestore-shorten-urls-bitly/package.json
  firestore-translate-text/package-lock.json
  firestore-translate-text/package.json
  rtdb-limit-child-nodes/package-lock.json
  rtdb-limit-child-nodes/package.json
  storage-resize-images/package-lock.json
  storage-resize-images/package.json
Labels: cla: yes, in-progress

#141 chore(*): update release notes URLs
  auth-mailchimp-sync/CHANGELOG.md
  auth-mailchimp-sync/extension.yaml
  delete-user-data/CHANGELOG.md
  delete-user-data/extension.yaml
  firestore-bigquery-export/CHANGELOG.md
  firestore-bigquery-export/extension.yaml
  firestore-counter/CHANGELOG.md
  firestore-counter/extension.yaml
  firestore-send-email/CHANGELOG.md
  firestore-send-email/extension.yaml
  firestore-shorten-urls-bitly/CHANGELOG.md
  firestore-shorten-urls-bitly/extension.yaml
  firestore-translate-text/CHANGELOG.md
  firestore-translate-text/extension.yaml
  rtdb-limit-child-nodes/CHANGELOG.md
  rtdb-limit-child-nodes/extension.yaml
  storage-resize-images/CHANGELOG.md
  storage-resize-images/extension.yaml
Labels: cla: yes, in-progress

#157 chore(*) Release notes for Jan 9 release
  storage-resize-images/CHANGELOG.md
  storage-resize-images/extension.yaml
Labels: cla: yes

#156 Jan 9, 2020 Release
  .huskyrc
  auth-mailchimp-sync/CHANGELOG.md
  auth-mailchimp-sync/extension.yaml
  auth-mailchimp-sync/package-lock.json
  auth-mailchimp-sync/package.json
  commitlint.config.js
  delete-user-data/CHANGELOG.md
  delete-user-data/extension.yaml
  delete-user-data/package-lock.json
  delete-user-data/package.json
  exts-test-data/package-lock.json
  firestore-bigquery-export/CHANGELOG.md
  firestore-bigquery-export/extension.yaml
  firestore-bigquery-export/guides/IMPORT_EXISTING_DOCUMENTS.md
  firestore-bigquery-export/package-lock.json
  firestore-bigquery-export/package.json
  firestore-counter/CHANGELOG.md
  firestore-counter/extension.yaml
  firestore-counter/package.json
  firestore-send-email/CHANGELOG.md
  firestore-send-email/extension.yaml
  firestore-send-email/package-lock.json
  firestore-send-email/package.json
  firestore-shorten-urls-bitly/CHANGELOG.md
  firestore-shorten-urls-bitly/extension.yaml
  firestore-shorten-urls-bitly/package-lock.json
  firestore-shorten-urls-bitly/package.json
  firestore-translate-text/CHANGELOG.md
  firestore-translate-text/extension.yaml
  firestore-translate-text/package-lock.json
  firestore-translate-text/package.json
  package-lock.json
  package.json
  rtdb-limit-child-nodes/CHANGELOG.md
  rtdb-limit-child-nodes/extension.yaml
  rtdb-limit-child-nodes/package-lock.json
  rtdb-limit-child-nodes/package.json
  storage-resize-images/CHANGELOG.md
  storage-resize-images/__tests__/extractFileNameWithoutExtension.ts
  storage-resize-images/extension.yaml
  storage-resize-images/functions/lib/index.js
  storage-resize-images/functions/lib/util.js
  storage-resize-images/functions/src/index.ts
  storage-resize-images/functions/src/util.ts
  storage-resize-images/package-lock.json
  storage-resize-images/package.json
Labels: cla: yes

#152 feat(delete-user-data): allow deleting directories & files
  delete-user-data/extension.yaml
  delete-user-data/functions/lib/index.js
  delete-user-data/functions/src/index.ts
Labels: cla: yes, in-progress

#149 Lower SHARDS_LIMIT to 100.
  firestore-counter/functions/src/worker.ts
Labels: cla: yes, do not merge, in-progress

#159 [all] clarify label & description of LOCATION param; note for default BigQuery location
  auth-mailchimp-sync/extension.yaml
  delete-user-data/extension.yaml
  firestore-bigquery-export/extension.yaml
  firestore-counter/extension.yaml
  firestore-send-email/extension.yaml
  firestore-shorten-urls-bitly/extension.yaml
  firestore-translate-text/extension.yaml
  rtdb-limit-child-nodes/extension.yaml
  storage-resize-images/extension.yaml
Labels: cla: yes

#161 docs(firestore-bigquery-export) Add instructions, information, and references for schema-views script
  firestore-bigquery-export/POSTINSTALL.md
  firestore-bigquery-export/PREINSTALL.md
  firestore-bigquery-export/guides/EXAMPLE_QUERIES.md
  firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md
Labels: cla: yes

#162 Release notes for Jan 16 release
  delete-user-data/CHANGELOG.md
  delete-user-data/extension.yaml
  firestore-counter/CHANGELOG.md
  firestore-counter/extension.yaml
Labels: cla: yes

#165 docs(firestore-bigquery-export) change heading level to an h4 for script sections in preinstall
  firestore-bigquery-export/PREINSTALL.md
Labels: cla: yes

#164 docs(firestore-bigquery-export) Add Firestore `reference` type to supported types in schema-views script instructions
  firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md
Labels: cla: yes

#163 Jan 16, 2020 release
  auth-mailchimp-sync/README.md
  auth-mailchimp-sync/extension.yaml
  delete-user-data/CHANGELOG.md
  delete-user-data/extension.yaml
  delete-user-data/functions/lib/index.js
  delete-user-data/functions/src/index.ts
  firestore-bigquery-export/POSTINSTALL.md
  firestore-bigquery-export/PREINSTALL.md
  firestore-bigquery-export/README.md
  firestore-bigquery-export/extension.yaml
  firestore-bigquery-export/guides/EXAMPLE_QUERIES.md
  firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md
  firestore-counter/CHANGELOG.md
  firestore-counter/README.md
  firestore-counter/extension.yaml
  firestore-counter/functions/lib/worker.js
  firestore-send-email/README.md
  firestore-send-email/extension.yaml
  firestore-shorten-urls-bitly/README.md
  firestore-shorten-urls-bitly/extension.yaml
  firestore-translate-text/README.md
  firestore-translate-text/extension.yaml
  rtdb-limit-child-nodes/README.md
  rtdb-limit-child-nodes/extension.yaml
  storage-resize-images/README.md
  storage-resize-images/extension.yaml
Labels: cla: yes

#177 docs(firestore-counter): change "Counter SDK" to "Client Sample"
  firestore-counter/POSTINSTALL.md
  firestore-counter/PREINSTALL.md
Labels: cla: yes

#172 docs(firestore-send-email): add note about bulk email service providers
  firestore-send-email/PREINSTALL.md
Labels: cla: yes

#158 docs(firestore-send-email): add instructions for email attachments
  firestore-send-email/POSTINSTALL.md
Labels: cla: yes, in-progress

#179 docs(firestore-counter) update max writes description #176
  firestore-counter/PREINSTALL.md
Labels: do not merge, documentation

#178 Jan 30, 2020 Release
  firestore-counter/POSTINSTALL.md
  firestore-counter/PREINSTALL.md
  firestore-counter/README.md
  firestore-send-email/POSTINSTALL.md
  firestore-send-email/PREINSTALL.md
  firestore-send-email/README.md
Labels: cla: yes
