Repository firebase/extensions, pull requests merged in 2020-03, with the labels that each got.

#205 chore(*): aligned the order and spacing of fields within extension.yaml files
  auth-mailchimp-sync/extension.yaml
  delete-user-data/extension.yaml
  firestore-bigquery-export/extension.yaml
  firestore-counter/extension.yaml
  firestore-send-email/extension.yaml
  firestore-shorten-urls-bitly/extension.yaml
  firestore-translate-text/extension.yaml
  rtdb-limit-child-nodes/extension.yaml
  storage-resize-images/extension.yaml
Labels: cla: yes, in-progress

#185 feat(firestore-send-email): update "Default FROM address" param to allow name to be added
  firestore-send-email/extension.yaml
Labels: cla: yes, in-progress

#183 fix(storage-resize-images): ensure content type is always available
  storage-resize-images/POSTINSTALL.md
  storage-resize-images/functions/lib/index.js
  storage-resize-images/functions/lib/logs.js
  storage-resize-images/functions/src/index.ts
  storage-resize-images/functions/src/logs.ts
Labels: cla: yes, do not merge, in-progress

#197 fix(fs-bq-import-collection): update bigquery lib and insert api usage
  firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
  firestore-bigquery-export/scripts/import/package.json
  firestore-bigquery-export/scripts/import/src/index.ts
Labels: cla: yes, in-progress

#193 fix(firestore-bigquery-export-gen-schema-view): create udfs if not exists
  firestore-bigquery-export/scripts/gen-schema-view/src/udf.ts
Labels: cla: yes, in-progress

#67 test(firestore-translate-text): Implement tests for translate extension
  .prettierignore
  .travis.yml
  codecov.yml
  firestore-translate-text/__tests__/__snapshots__/config.test.ts.snap
  firestore-translate-text/__tests__/config.test.ts
  firestore-translate-text/__tests__/functions.test.ts
  firestore-translate-text/__tests__/jest.setup.ts
  firestore-translate-text/__tests__/mocks/console.ts
  firestore-translate-text/__tests__/mocks/firestore.ts
  firestore-translate-text/__tests__/mocks/translate.ts
  firestore-translate-text/__tests__/test.types.d.ts
  firestore-translate-text/__tests__/tsconfig.json
  firestore-translate-text/functions/lib/index.js
  firestore-translate-text/functions/lib/logs.js
  firestore-translate-text/functions/lib/logs/index.js
  firestore-translate-text/functions/lib/logs/messages.js
  firestore-translate-text/functions/src/index.ts
  firestore-translate-text/functions/src/logs/index.ts
  firestore-translate-text/functions/src/logs/messages.ts
  firestore-translate-text/jest.config.js
  firestore-translate-text/package-lock.json
  firestore-translate-text/package.json
  jest.config.js
  package-lock.json
  package.json
Labels: cla: yes, in-progress

#216 firestore-send-email param description edit
  firestore-send-email/extension.yaml
Labels: cla: yes

#215 Release notes for 3/5/2020
  firestore-bigquery-export/CHANGELOG.md
  firestore-bigquery-export/extension.yaml
  firestore-send-email/CHANGELOG.md
  firestore-send-email/extension.yaml
  storage-resize-images/CHANGELOG.md
  storage-resize-images/extension.yaml
Labels: cla: yes

#214 March 3, 2020 Release
  .prettierignore
  .travis.yml
  CONTRIBUTING.md
  auth-mailchimp-sync/extension.yaml
  codecov.yml
  delete-user-data/extension.yaml
  firestore-bigquery-export/CHANGELOG.md
  firestore-bigquery-export/extension.yaml
  firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
  firestore-bigquery-export/scripts/gen-schema-view/src/udf.ts
  firestore-bigquery-export/scripts/import/package.json
  firestore-bigquery-export/scripts/import/src/index.ts
  firestore-counter/extension.yaml
  firestore-send-email/CHANGELOG.md
  firestore-send-email/extension.yaml
  firestore-shorten-urls-bitly/extension.yaml
  firestore-translate-text/__tests__/__snapshots__/config.test.ts.snap
  firestore-translate-text/__tests__/config.test.ts
  firestore-translate-text/__tests__/functions.test.ts
  firestore-translate-text/__tests__/jest.setup.ts
  firestore-translate-text/__tests__/mocks/console.ts
  firestore-translate-text/__tests__/mocks/firestore.ts
  firestore-translate-text/__tests__/mocks/translate.ts
  firestore-translate-text/__tests__/test.types.d.ts
  firestore-translate-text/__tests__/tsconfig.json
  firestore-translate-text/extension.yaml
  firestore-translate-text/functions/lib/index.js
  firestore-translate-text/functions/lib/logs.js
  firestore-translate-text/functions/lib/logs/index.js
  firestore-translate-text/functions/lib/logs/messages.js
  firestore-translate-text/functions/src/index.ts
  firestore-translate-text/functions/src/logs/index.ts
  firestore-translate-text/functions/src/logs/messages.ts
  firestore-translate-text/jest.config.js
  firestore-translate-text/package-lock.json
  firestore-translate-text/package.json
  jest.config.js
  package-lock.json
  package.json
  rtdb-limit-child-nodes/extension.yaml
  storage-resize-images/CHANGELOG.md
  storage-resize-images/POSTINSTALL.md
  storage-resize-images/extension.yaml
  storage-resize-images/functions/lib/index.js
  storage-resize-images/functions/lib/logs.js
  storage-resize-images/functions/src/index.ts
  storage-resize-images/functions/src/logs.ts
Labels: cla: yes

#217 chore: update codeowners
  .github/CODEOWNERS
Labels: cla: yes, in-review

#224 refactor(firestore-translate-text): clarify log message
  firestore-translate-text/functions/lib/logs/messages.js
  firestore-translate-text/functions/src/logs/messages.ts
Labels: cla: yes, in-progress

#222 refactor(firestore-translate-text): move package.json into functions dir
  firestore-translate-text/extension.yaml
  firestore-translate-text/functions/__tests__/__snapshots__/config.test.ts.snap
  firestore-translate-text/functions/__tests__/config.test.ts
  firestore-translate-text/functions/__tests__/functions.test.ts
  firestore-translate-text/functions/__tests__/jest.setup.ts
  firestore-translate-text/functions/__tests__/mocks/console.ts
  firestore-translate-text/functions/__tests__/mocks/firestore.ts
  firestore-translate-text/functions/__tests__/mocks/translate.ts
  firestore-translate-text/functions/__tests__/test.types.d.ts
  firestore-translate-text/functions/__tests__/tsconfig.json
  firestore-translate-text/functions/jest.config.js
  firestore-translate-text/functions/package.json
  firestore-translate-text/functions/tsconfig.json
  firestore-translate-text/package-lock.json
  firestore-translate-text/tsconfig.json
  jest.config.js
  lerna.json
Labels: cla: yes

#210 docs(firestore-shorten-urls-bitly): changed Bit.ly to Bitly in PREINSTALL file
  firestore-shorten-urls-bitly/PREINSTALL.md
Labels: cla: yes

#219 fix(delete-user-data): update firebase-tools version
  delete-user-data/package-lock.json
  delete-user-data/package.json
Labels: cla: yes

#227 refactor(firestore-counter): use handlers
  firestore-counter/functions/lib/index.js
  firestore-counter/functions/src/index.ts
Labels: cla: yes, in-progress

#231 chore(*): release notes for March 19 release
  delete-user-data/CHANGELOG.md
  delete-user-data/extension.yaml
Labels: cla: yes

#229 Mar 19, 2020 Release
  .github/CODEOWNERS
  .gitignore
  auth-mailchimp-sync/functions/lib/index.js
  auth-mailchimp-sync/functions/lib/logs.js
  auth-mailchimp-sync/package-lock.json
  delete-user-data/CHANGELOG.md
  delete-user-data/extension.yaml
  delete-user-data/package-lock.json
  delete-user-data/package.json
  exts-test-data/package-lock.json
  firestore-bigquery-export/package-lock.json
  firestore-counter/README.md
  firestore-counter/functions/lib/index.js
  firestore-counter/functions/src/index.ts
  firestore-send-email/README.md
  firestore-send-email/functions/lib/index.js
  firestore-send-email/functions/lib/templates.js
  firestore-send-email/package-lock.json
  firestore-shorten-urls-bitly/PREINSTALL.md
  firestore-shorten-urls-bitly/README.md
  firestore-shorten-urls-bitly/functions/lib/abstract-shortener.js
  firestore-shorten-urls-bitly/functions/lib/index.js
  firestore-shorten-urls-bitly/functions/lib/logs.js
  firestore-shorten-urls-bitly/package-lock.json
  firestore-translate-text/README.md
  firestore-translate-text/extension.yaml
  firestore-translate-text/functions/__tests__/__snapshots__/config.test.ts.snap
  firestore-translate-text/functions/__tests__/config.test.ts
  firestore-translate-text/functions/__tests__/functions.test.ts
  firestore-translate-text/functions/__tests__/jest.setup.ts
  firestore-translate-text/functions/__tests__/mocks/console.ts
  firestore-translate-text/functions/__tests__/mocks/firestore.ts
  firestore-translate-text/functions/__tests__/mocks/translate.ts
  firestore-translate-text/functions/__tests__/test.types.d.ts
  firestore-translate-text/functions/__tests__/tsconfig.json
  firestore-translate-text/functions/jest.config.js
  firestore-translate-text/functions/lib/index.js
  firestore-translate-text/functions/lib/logs/messages.js
  firestore-translate-text/functions/package.json
  firestore-translate-text/functions/src/logs/messages.ts
  firestore-translate-text/functions/tsconfig.json
  firestore-translate-text/package-lock.json
  firestore-translate-text/tsconfig.json
  jest.config.js
  lerna.json
  package-lock.json
  rtdb-limit-child-nodes/functions/lib/index.js
  rtdb-limit-child-nodes/package-lock.json
  storage-resize-images/functions/lib/index.js
  storage-resize-images/package-lock.json
Labels: cla: yes

#234 docs(firestore-send-email): Backtick around angled brackets within extension.yaml
  firestore-send-email/extension.yaml
Labels: cla: yes

#240 docs(*): performed copy-edits to POSTINSTALL files
  auth-mailchimp-sync/POSTINSTALL.md
  delete-user-data/POSTINSTALL.md
  firestore-bigquery-export/POSTINSTALL.md
  firestore-counter/POSTINSTALL.md
  firestore-send-email/POSTINSTALL.md
  firestore-shorten-urls-bitly/POSTINSTALL.md
  firestore-translate-text/POSTINSTALL.md
  rtdb-limit-child-nodes/POSTINSTALL.md
  storage-resize-images/POSTINSTALL.md
Labels: cla: yes
