Repository firebase/extensions, pull requests merged in 2020-08, with the labels that each got.

#392 Update all other Cloud Firestore console deeplinks in POSTINSTALLs
  firestore-bigquery-export/POSTINSTALL.md
  firestore-shorten-urls-bitly/POSTINSTALL.md
  firestore-translate-text/POSTINSTALL.md
Labels: cla: yes, do not merge

#390 send-email: Fix console deeplinks to Firestore for upcoming Cloud Firestore/Realtime Database split
  firestore-send-email/POSTINSTALL.md
Labels: cla: yes

#420 docs(firestore-bigquery-export): add BigQuery packages' README files
  firestore-bigquery-export/firestore-bigquery-change-tracker/README.md
  firestore-bigquery-export/scripts/gen-schema-view/README.md
  firestore-bigquery-export/scripts/import/README.md
Labels: cla: yes, in-review

#280 test(firestore-bigquery-export): Big Query sub-module tests
  jest.config.js
  lerna.json
Labels: cla: yes, in-review

#418 feat(firestore-bigquery-export): Add validation regex for collection path parameter.
  firestore-bigquery-export/extension.yaml
Labels: cla: yes, in-review

#407 chore: disable patch status coverage reporting
  codecov.yml
Labels: cla: yes, in-review

#413 chore(firestore-translate-text): migration to Node.js v10
  firestore-translate-text/PREINSTALL.md
  firestore-translate-text/README.md
  firestore-translate-text/extension.yaml
  firestore-translate-text/functions/__tests__/config.test.ts
  firestore-translate-text/functions/__tests__/functions.test.ts
  firestore-translate-text/functions/__tests__/jest.setup.ts
  firestore-translate-text/functions/__tests__/mocks/console.ts
  firestore-translate-text/functions/__tests__/tsconfig.json
  firestore-translate-text/functions/lib/index.js
  firestore-translate-text/functions/lib/logs/index.js
  firestore-translate-text/functions/package.json
  firestore-translate-text/functions/src/index.ts
  firestore-translate-text/functions/src/logs/index.ts
  firestore-translate-text/functions/tsconfig.json
Labels: cla: yes, do not merge, in-review

#436 chore(firestore-bigquery-export): migration to Node.js v10
  firestore-bigquery-export/PREINSTALL.md
  firestore-bigquery-export/README.md
  firestore-bigquery-export/extension.yaml
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/logs.ts
  firestore-bigquery-export/functions/lib/index.js
  firestore-bigquery-export/functions/lib/logs.js
  firestore-bigquery-export/functions/lib/util.js
  firestore-bigquery-export/package.json
  firestore-bigquery-export/tsconfig.json
Labels: cla: yes, in-review

#414 chore(firestore-counter): migration to Node.js v10
  firestore-counter/PREINSTALL.md
  firestore-counter/README.md
  firestore-counter/extension.yaml
  firestore-counter/functions/README.md
  firestore-counter/functions/lib/controller.js
  firestore-counter/functions/lib/index.js
  firestore-counter/functions/lib/worker.js
  firestore-counter/functions/package.json
  firestore-counter/functions/src/controller.ts
  firestore-counter/functions/src/worker.ts
  firestore-counter/functions/tsconfig.json
Labels: cla: yes, do not merge, in-review

#428 chore(firestore-send-email): migration to Node.js v10
  firestore-send-email/PREINSTALL.md
  firestore-send-email/README.md
  firestore-send-email/extension.yaml
  firestore-send-email/functions/README.md
  firestore-send-email/functions/__tests__/functions.test.ts
  firestore-send-email/functions/lib/index.js
  firestore-send-email/functions/lib/logs.js
  firestore-send-email/functions/lib/templates.js
  firestore-send-email/functions/package.json
  firestore-send-email/functions/src/logs.ts
  firestore-send-email/functions/src/templates.ts
  firestore-send-email/functions/tsconfig.json
Labels: cla: yes, in-review

#430 chore(auth-mailchimp-sync): migration to Node.js v10
  auth-mailchimp-sync/PREINSTALL.md
  auth-mailchimp-sync/README.md
  auth-mailchimp-sync/extension.yaml
  auth-mailchimp-sync/functions/README.md
  auth-mailchimp-sync/functions/__tests__/functions.test.ts
  auth-mailchimp-sync/functions/lib/index.js
  auth-mailchimp-sync/functions/lib/logs.js
  auth-mailchimp-sync/functions/src/logs.ts
  auth-mailchimp-sync/functions/tsconfig.json
Labels: cla: yes, in-review

#432 chore(firestore-shorten-urls-bitly): migration to Node.js v10
  firestore-shorten-urls-bitly/PREINSTALL.md
  firestore-shorten-urls-bitly/extension.yaml
  firestore-shorten-urls-bitly/functions/README.md
  firestore-shorten-urls-bitly/functions/lib/abstract-shortener.js
  firestore-shorten-urls-bitly/functions/lib/index.js
  firestore-shorten-urls-bitly/functions/lib/logs.js
  firestore-shorten-urls-bitly/functions/package.json
  firestore-shorten-urls-bitly/functions/src/logs.ts
  firestore-shorten-urls-bitly/functions/tsconfig.json
Labels: cla: yes, in-review

#433 chore(storage-resize-images): migration to Node.js v10
  storage-resize-images/PREINSTALL.md
  storage-resize-images/README.md
  storage-resize-images/extension.yaml
  storage-resize-images/functions/lib/index.js
  storage-resize-images/functions/lib/logs.js
  storage-resize-images/functions/src/logs.ts
  storage-resize-images/package.json
  storage-resize-images/tsconfig.json
Labels: cla: yes, in-review

#434 chore(rtdb-limit-child-nodes): migration to Node.js v10
  rtdb-limit-child-nodes/PREINSTALL.md
  rtdb-limit-child-nodes/extension.yaml
  rtdb-limit-child-nodes/functions/README.md
  rtdb-limit-child-nodes/functions/lib/index.js
  rtdb-limit-child-nodes/functions/lib/logs.js
  rtdb-limit-child-nodes/functions/package.json
  rtdb-limit-child-nodes/functions/src/logs.ts
  rtdb-limit-child-nodes/functions/tsconfig.json
Labels: cla: yes, in-review

#438 chore(*): update preinstalls with latest recommended billing wording
  auth-mailchimp-sync/PREINSTALL.md
  auth-mailchimp-sync/functions/README.md
  delete-user-data/PREINSTALL.md
  delete-user-data/README.md
  delete-user-data/functions/README.md
  firestore-bigquery-export/PREINSTALL.md
  firestore-bigquery-export/README.md
  firestore-counter/PREINSTALL.md
  firestore-counter/functions/README.md
  firestore-send-email/PREINSTALL.md
  firestore-send-email/functions/README.md
  firestore-shorten-urls-bitly/PREINSTALL.md
  firestore-shorten-urls-bitly/functions/README.md
  firestore-translate-text/PREINSTALL.md
  firestore-translate-text/README.md
  rtdb-limit-child-nodes/PREINSTALL.md
  rtdb-limit-child-nodes/functions/README.md
  storage-resize-images/PREINSTALL.md
  storage-resize-images/README.md
Labels: cla: yes

#440 chore(*) Bump versions and add releaes notes for Node.js 10 release
  auth-mailchimp-sync/CHANGELOG.md
  auth-mailchimp-sync/extension.yaml
  delete-user-data/CHANGELOG.md
  delete-user-data/extension.yaml
  firestore-bigquery-export/CHANGELOG.md
  firestore-bigquery-export/extension.yaml
  firestore-counter/CHANGELOG.md
  firestore-counter/extension.yaml
  firestore-send-email/CHANGELOG.md
  firestore-send-email/extension.yaml
  firestore-shorten-urls-bitly/CHANGELOG.md
  firestore-shorten-urls-bitly/extension.yaml
  firestore-translate-text/CHANGELOG.md
  firestore-translate-text/extension.yaml
  rtdb-limit-child-nodes/CHANGELOG.md
  rtdb-limit-child-nodes/extension.yaml
  storage-resize-images/CHANGELOG.md
  storage-resize-images/extension.yaml
Labels: cla: yes
