Repository firebase/extensions, pull requests merged in 2020-09, with the labels that each got.

#417 fix(storage-resize-images): ignore gzipped images
  firestore-bigquery-export/functions/lib/logs.js
  firestore-bigquery-export/functions/lib/util.js
  storage-resize-images/functions/lib/index.js
  storage-resize-images/functions/lib/logs.js
  storage-resize-images/functions/src/index.ts
  storage-resize-images/functions/src/logs.ts
Labels: cla: yes, in-review

#419 feat(firestore-send-email): adds support for Handlebars partials
  firestore-send-email/POSTINSTALL.md
  firestore-send-email/functions/lib/templates.js
  firestore-send-email/functions/src/templates.ts
Labels: cla: yes

#388 chore(*): add new cloud functions locations
  auth-mailchimp-sync/extension.yaml
  auth-mailchimp-sync/functions/package.json
  delete-user-data/extension.yaml
  delete-user-data/functions/package.json
  firestore-bigquery-export/extension.yaml
  firestore-bigquery-export/package.json
  firestore-counter/extension.yaml
  firestore-counter/functions/package.json
  firestore-send-email/extension.yaml
  firestore-send-email/functions/package.json
  firestore-shorten-urls-bitly/extension.yaml
  firestore-shorten-urls-bitly/functions/package.json
  firestore-translate-text/extension.yaml
  firestore-translate-text/functions/package.json
  rtdb-limit-child-nodes/extension.yaml
  rtdb-limit-child-nodes/functions/package.json
  storage-resize-images/extension.yaml
  storage-resize-images/package.json
Labels: cla: yes, do not merge, in-review

#70 feat(firestore-shorten-urls-dynamic-links): introduce Dynamic Links URL shortening extension
  firestore-shorten-urls-dynamic-links/POSTINSTALL.md
  firestore-shorten-urls-dynamic-links/PREINSTALL.md
  firestore-shorten-urls-dynamic-links/README.md
  firestore-shorten-urls-dynamic-links/extension.yaml
  firestore-shorten-urls-dynamic-links/functions/lib/abstract-shortener.js
  firestore-shorten-urls-dynamic-links/functions/lib/config.js
  firestore-shorten-urls-dynamic-links/functions/lib/index.js
  firestore-shorten-urls-dynamic-links/functions/lib/logs.js
  firestore-shorten-urls-dynamic-links/functions/package.json
  firestore-shorten-urls-dynamic-links/functions/src/abstract-shortener.ts
  firestore-shorten-urls-dynamic-links/functions/src/config.ts
  firestore-shorten-urls-dynamic-links/functions/src/index.ts
  firestore-shorten-urls-dynamic-links/functions/src/logs.ts
  firestore-shorten-urls-dynamic-links/functions/tsconfig.json
  lerna.json
Labels: blocked, cla: yes, do not merge

#449 Update changelogs for September 10, 2020 release
  auth-mailchimp-sync/CHANGELOG.md
  auth-mailchimp-sync/extension.yaml
  delete-user-data/CHANGELOG.md
  delete-user-data/extension.yaml
  firestore-bigquery-export/CHANGELOG.md
  firestore-bigquery-export/extension.yaml
  firestore-counter/CHANGELOG.md
  firestore-counter/extension.yaml
  firestore-send-email/CHANGELOG.md
  firestore-send-email/extension.yaml
  firestore-shorten-urls-bitly/CHANGELOG.md
  firestore-shorten-urls-bitly/extension.yaml
  firestore-translate-text/CHANGELOG.md
  firestore-translate-text/extension.yaml
  rtdb-limit-child-nodes/CHANGELOG.md
  rtdb-limit-child-nodes/extension.yaml
  storage-resize-images/CHANGELOG.md
  storage-resize-images/extension.yaml
Labels: cla: yes

#450 docs(firestore-translate-text): multiple inputs
  firestore-translate-text/POSTINSTALL.md
Labels: cla: yes

#354 feat(firestore-bigquery-export): support collectionGroup queries
  firestore-bigquery-export/guides/IMPORT_EXISTING_DOCUMENTS.md
  firestore-bigquery-export/scripts/import/package.json
  firestore-bigquery-export/scripts/import/src/index.ts
Labels: cla: yes, in-review

#455 Changelog for sept 24 release
  firestore-translate-text/CHANGELOG.md
  firestore-translate-text/extension.yaml
Labels: cla: yes

#454 Sept 24 2020 Release
  auth-mailchimp-sync/functions/README.md
  delete-user-data/functions/README.md
  delete-user-data/functions/package.json
  firestore-bigquery-export/guides/IMPORT_EXISTING_DOCUMENTS.md
  firestore-bigquery-export/scripts/import/package.json
  firestore-bigquery-export/scripts/import/src/index.ts
  firestore-send-email/functions/README.md
  firestore-translate-text/CHANGELOG.md
  firestore-translate-text/POSTINSTALL.md
  firestore-translate-text/extension.yaml
  firestore-translate-text/functions/lib/index.js
  firestore-translate-text/functions/lib/logs/index.js
  firestore-translate-text/functions/lib/logs/messages.js
  firestore-translate-text/functions/lib/validators.js
  rtdb-limit-child-nodes/functions/README.md
Labels: cla: yes
