Repository firebase/extensions, pull requests merged in 2020-04, with the labels that each got.

#244 test(firestore-bigquery-export) Use`mocha` instead of `jest` for tests
  firestore-bigquery-export/DEVSETUP.md
  firestore-bigquery-export/docs/images/firestore-bigquery-export-dep-diagram.svg
  firestore-bigquery-export/firestore-bigquery-change-tracker/mocha.opts
  firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
  firestore-bigquery-export/firestore-bigquery-change-tracker/tsconfig.json
  firestore-bigquery-export/functions/package.json
  firestore-bigquery-export/mocha.opts
  firestore-bigquery-export/package.json
  firestore-bigquery-export/scripts/gen-schema-view/mocha.opts
  firestore-bigquery-export/scripts/gen-schema-view/package.json
  firestore-bigquery-export/scripts/gen-schema-view/src/test/schema-loader-utils/schema-loader-utils.spec.ts
  firestore-bigquery-export/scripts/gen-schema-view/tsconfig.json
  firestore-bigquery-export/scripts/import/package.json
  firestore-bigquery-export/tsconfig.json
Labels: cla: yes

#138 feat(firestore-bigquery-export): explicit bigquery schemas for raw changelog and schema views
  firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/schema.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/snapshot.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/index.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/tsconfig.json
  firestore-bigquery-export/functions/lib/index.js
  firestore-bigquery-export/functions/src/index.ts
  firestore-bigquery-export/package.json
  firestore-bigquery-export/scripts/gen-schema-view/package.json
  firestore-bigquery-export/scripts/gen-schema-view/schemas/test.json
  firestore-bigquery-export/scripts/gen-schema-view/schemas/user-schema-version-login.json
  firestore-bigquery-export/scripts/gen-schema-view/schemas/user_array.json
  firestore-bigquery-export/scripts/gen-schema-view/schemas/user_full.json
  firestore-bigquery-export/scripts/gen-schema-view/src/schema.ts
  firestore-bigquery-export/scripts/gen-schema-view/src/snapshot.ts
  firestore-bigquery-export/scripts/gen-schema-view/src/test/bigquery/schema.spec.ts
  firestore-bigquery-export/scripts/gen-schema-view/src/test/bigquery/snapshot.spec.ts
  firestore-bigquery-export/scripts/import/package.json
  firestore-bigquery-export/scripts/import/tsconfig.json
Labels: cla: yes

#249 docs(firestore-bigquery-export) Release notes for April 7 release
  firestore-bigquery-export/CHANGELOG.md
  firestore-bigquery-export/extension.yaml
Labels: cla: yes

#248 04/07/2020 Release
  auth-mailchimp-sync/POSTINSTALL.md
  delete-user-data/POSTINSTALL.md
  firestore-bigquery-export/CHANGELOG.md
  firestore-bigquery-export/DEVSETUP.md
  firestore-bigquery-export/POSTINSTALL.md
  firestore-bigquery-export/docs/images/firestore-bigquery-export-dep-diagram.svg
  firestore-bigquery-export/extension.yaml
  firestore-bigquery-export/firestore-bigquery-change-tracker/mocha.opts
  firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/schema.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/snapshot.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/index.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/tsconfig.json
  firestore-bigquery-export/functions/lib/index.js
  firestore-bigquery-export/functions/package.json
  firestore-bigquery-export/functions/src/index.ts
  firestore-bigquery-export/mocha.opts
  firestore-bigquery-export/package.json
  firestore-bigquery-export/scripts/gen-schema-view/mocha.opts
  firestore-bigquery-export/scripts/gen-schema-view/package.json
  firestore-bigquery-export/scripts/gen-schema-view/schemas/test.json
  firestore-bigquery-export/scripts/gen-schema-view/schemas/user-schema-version-login.json
  firestore-bigquery-export/scripts/gen-schema-view/schemas/user_array.json
  firestore-bigquery-export/scripts/gen-schema-view/schemas/user_full.json
  firestore-bigquery-export/scripts/gen-schema-view/src/schema.ts
  firestore-bigquery-export/scripts/gen-schema-view/src/snapshot.ts
  firestore-bigquery-export/scripts/gen-schema-view/src/test/bigquery/schema.spec.ts
  firestore-bigquery-export/scripts/gen-schema-view/src/test/bigquery/snapshot.spec.ts
  firestore-bigquery-export/scripts/gen-schema-view/src/test/schema-loader-utils/schema-loader-utils.spec.ts
  firestore-bigquery-export/scripts/gen-schema-view/tsconfig.json
  firestore-bigquery-export/scripts/import/package.json
  firestore-bigquery-export/scripts/import/tsconfig.json
  firestore-bigquery-export/tsconfig.json
  firestore-counter/POSTINSTALL.md
  firestore-send-email/POSTINSTALL.md
  firestore-send-email/README.md
  firestore-send-email/extension.yaml
  firestore-shorten-urls-bitly/POSTINSTALL.md
  firestore-translate-text/POSTINSTALL.md
  rtdb-limit-child-nodes/POSTINSTALL.md
  storage-resize-images/POSTINSTALL.md
Labels: cla: yes

#258 docs(firestore-bigquery-export): Update DEVSETUP.md
  firestore-bigquery-export/DEVSETUP.md
Labels: cla: yes

#238 fix(firestore-bigquery-export): fixed "Converting circular structure to JSON" error (issue #236).
  firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
  firestore-bigquery-export/package.json
Labels: cla: yes

#257 fix(firestore-bigquery-export): add package & update exports
  firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/index.ts
  firestore-bigquery-export/scripts/gen-schema-view/.gitignore
  firestore-bigquery-export/scripts/gen-schema-view/package.json
Labels: cla: yes

#207 fix(storage-resize-images): switched imagemagick for sharp library
  storage-resize-images/functions/lib/index.js
  storage-resize-images/functions/src/index.ts
  storage-resize-images/package.json
  storage-resize-images/yarn.lock
Labels: cla: yes, in-progress

#263 commit jest configs for firestore-bigquery-export packages
  firestore-bigquery-export/POSTINSTALL.md
  firestore-bigquery-export/PREINSTALL.md
  firestore-bigquery-export/README.md
  firestore-bigquery-export/extension.yaml
  firestore-bigquery-export/firestore-bigquery-change-tracker/jest.config.js
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/snapshot.test.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/fixtures/sql/latestConsistentSnapshot.txt
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/fixtures/sql/latestConsistentSnapshotNoGroupBy.txt
  firestore-bigquery-export/scripts/gen-schema-view/jest.config.js
  firestore-bigquery-export/scripts/gen-schema-view/package.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/bigquery/schema.test.ts
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/bigquery/snapshot.test.ts
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schema-files/deep-directory/1/2/leaf-schemas-1.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schema-files/deep-directory/1/2/leaf-schemas-2.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schema-files/deep-directory/1/2/leaf-schemas-3.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schema-files/deep-directory/1/2/leaf-schemas-4.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schema-files/deep-directory/1/2/leaf-schemas-5.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schema-files/deep-directory/1/other-schemas-1.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schema-files/deep-directory/1/other-schemas-2.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schema-files/deep-directory/1/other-schemas-3.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schema-files/deep-directory/1/other-schemas-4.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schema-files/deep-directory/1/other-schemas-5.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schema-files/full-directory/schema-1.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schema-files/full-directory/schema-1.txt
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schema-files/full-directory/schema-2.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schema-files/full-directory/schema-2.txt
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schema-files/full-directory/schema-3.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schema-files/full-directory/schema-3.txt
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schema-files/full-directory/schema-4.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schema-files/full-directory/schema-4.txt
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schema-files/full-directory/schema-5.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schema-files/full-directory/schema-5.txt
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schemas/arraysNestedInMapsSchema.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schemas/emptyMapSchema.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schemas/emptySchema.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schemas/fullSchema.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schemas/fullSchemaSquared.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schemas/nestedMapSchema.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/schemas/referenceSchema.json
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/arraysNestedInMapsSchema.txt
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/emptyMapSchema.txt
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/emptySchemaChangeLog.txt
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/emptySchemaLatest.txt
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/emptySchemaLatestFromView.txt
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/fullSchemaChangeLog.txt
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/fullSchemaLatest.txt
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/fullSchemaLatestFromView.txt
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/fullSchemaLatestLatestFromView.txt
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/fullSchemaSquared.txt
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/latestConsistentSnapshot.txt
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/latestConsistentSnapshotNoGroupBy.txt
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/nestedMapSchemaChangeLog.txt
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/referenceSchema.txt
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/schema-loader-utils/schema-loader-utils.test.ts
Labels: cla: yes

#270 fix(firestore-bigquery-export): fix bug where modules were not sharing the same Firestore DocumentReference (issue #265)
  firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
  firestore-bigquery-export/package.json
  firestore-bigquery-export/scripts/gen-schema-view/package.json
Labels: cla: yes

#275 Release notes for April 21, 2020 Release
  firestore-bigquery-export/CHANGELOG.md
  storage-resize-images/CHANGELOG.md
Labels: cla: yes

#277 chore(*) Increment extension versions
  firestore-bigquery-export/extension.yaml
  storage-resize-images/extension.yaml
Labels: cla: yes

#278 fix(storage-resize-image): fix Sharp version to v0.23 to preserve compatibility with Node 8
  storage-resize-images/functions/lib/index.js
  storage-resize-images/package.json
Labels: cla: yes

#282 fix(storage-resize-image): fix sharp to v0.23 (#278)
  auth-mailchimp-sync/functions/lib/index.js
  auth-mailchimp-sync/functions/lib/logs.js
  firestore-bigquery-export/CHANGELOG.md
  firestore-bigquery-export/extension.yaml
  firestore-send-email/functions/lib/index.js
  firestore-send-email/functions/lib/templates.js
  firestore-shorten-urls-bitly/functions/lib/abstract-shortener.js
  firestore-shorten-urls-bitly/functions/lib/index.js
  firestore-shorten-urls-bitly/functions/lib/logs.js
  storage-resize-images/CHANGELOG.md
  storage-resize-images/extension.yaml
  storage-resize-images/functions/lib/index.js
  storage-resize-images/package.json
Labels: cla: yes

#273 Update and rename DEVSETUP.md to CONTRIBUTING.md
  firestore-bigquery-export/CONTRIBUTING.md
Labels: cla: yes

#272 chore: initial GitHub releases action
  .github/workflows/release.yml
  .github/workflows/scripts/release.sh
Labels: cla: yes

#279 fix(storage-resizes-images) Fixes issue where resized image is not rendered in Firebase Console (Issue #140)
  storage-resize-images/extension.yaml
  storage-resize-images/functions/lib/index.js
  storage-resize-images/functions/src/index.ts
Labels: cla: yes, in-review

#288 chore(*): add europe-west3 location
  auth-mailchimp-sync/extension.yaml
  delete-user-data/extension.yaml
  firestore-bigquery-export/extension.yaml
  firestore-counter/extension.yaml
  firestore-send-email/extension.yaml
  firestore-shorten-urls-bitly/extension.yaml
  firestore-translate-text/extension.yaml
  rtdb-limit-child-nodes/extension.yaml
  storage-resize-images/extension.yaml
Labels: cla: yes

#291 chore: remove husky commit hook
  .huskyrc
  package.json
Labels: cla: yes

#281 chore(*): reorder fields in extension.yaml
  auth-mailchimp-sync/extension.yaml
  delete-user-data/extension.yaml
  firestore-bigquery-export/extension.yaml
  firestore-counter/extension.yaml
  firestore-send-email/extension.yaml
  firestore-shorten-urls-bitly/extension.yaml
  firestore-translate-text/extension.yaml
  rtdb-limit-child-nodes/extension.yaml
  storage-resize-images/extension.yaml
Labels: cla: yes

#287 fix(firestore-bigquery-export): fix "TypeError: Cannot read property 'constructor' of null" (Issue #284)
  firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
  firestore-bigquery-export/package.json
Labels: cla: yes
