Repository firebase/extensions, pull requests merged in 2021-08, with the labels that each got.

#713 fix(firestore-send-email): added fallback for finding email templates
  firestore-send-email/functions/lib/logs.js
  firestore-send-email/functions/lib/templates.js
  firestore-send-email/functions/src/logs.ts
  firestore-send-email/functions/src/templates.ts
Labels: cla: yes

#699 chore(delete-user-data): update rtdb to be optional
  delete-user-data/extension.yaml
Labels: cla: yes, in-review

#656 fix(firestore-bigquery-export): Improved import script
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
  firestore-bigquery-export/scripts/import/package.json
  firestore-bigquery-export/scripts/import/src/config.ts
  firestore-bigquery-export/scripts/import/src/index.ts
  firestore-bigquery-export/scripts/import/src/run.ts
  firestore-bigquery-export/scripts/import/src/types.ts
  firestore-bigquery-export/scripts/import/src/worker.ts
  firestore-bigquery-export/scripts/import/tsconfig.json
Labels: cla: yes, in-review

#701 chore: remove package-lock.json from .gitignore
  .gitignore
  firestore-counter/.gitignore
Labels: cla: yes, in-review

#706 fix(firestore-send-email) removed duplicate warsaw location
  firestore-send-email/extension.yaml
Labels: cla: yes

#721 chore(*): Regenerate readmes
  storage-resize-images/README.md
Labels: cla: yes

#725 Update versions of firestore-bigquery-export scripts
  firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
  firestore-bigquery-export/scripts/import/package.json
Labels: cla: yes

#723 Release Notes for Aug. 19 Release
  delete-user-data/CHANGELOG.md
  delete-user-data/extension.yaml
  firestore-bigquery-export/CHANGELOG.md
  firestore-bigquery-export/extension.yaml
  firestore-send-email/CHANGELOG.md
  firestore-send-email/extension.yaml
Labels: cla: yes

#722 Aug. 19 Release
  .gitignore
  delete-user-data/CHANGELOG.md
  delete-user-data/extension.yaml
  firestore-bigquery-export/CHANGELOG.md
  firestore-bigquery-export/extension.yaml
  firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
  firestore-bigquery-export/functions/__tests__/tsconfig.json
  firestore-bigquery-export/functions/package.json
  firestore-bigquery-export/functions/tsconfig.json
  firestore-bigquery-export/scripts/import/package.json
  firestore-bigquery-export/scripts/import/src/config.ts
  firestore-bigquery-export/scripts/import/src/index.ts
  firestore-bigquery-export/scripts/import/src/run.ts
  firestore-bigquery-export/scripts/import/src/types.ts
  firestore-bigquery-export/scripts/import/src/worker.ts
  firestore-bigquery-export/scripts/import/tsconfig.json
  firestore-counter/.gitignore
  firestore-send-email/CHANGELOG.md
  firestore-send-email/extension.yaml
  firestore-send-email/functions/lib/logs.js
  firestore-send-email/functions/lib/templates.js
  firestore-send-email/functions/src/logs.ts
  firestore-send-email/functions/src/templates.ts
  firestore-translate-text/functions/package.json
  storage-resize-images/README.md
Labels: cla: no

#715 ci: drop Node.js v10 and add v14 to tests job
  .github/workflows/test.yml
Labels: cla: yes, in-review
