Repository firebase/extensions, pull requests merged in 2022-03, with the labels that each got.

#810 chore(storage-resize-images):added prepare script
  storage-resize-images/functions/.gitignore
  storage-resize-images/functions/lib/config.js
  storage-resize-images/functions/lib/index.js
  storage-resize-images/functions/lib/logs.js
  storage-resize-images/functions/lib/resize-image.js
  storage-resize-images/functions/lib/util.js
  storage-resize-images/functions/package-lock.json
  storage-resize-images/functions/package.json
  storage-resize-images/functions/tsconfig.json
Labels: cla: yes

#812 chore(rtdb-limit-child-nodes):added prepare script
  rtdb-limit-child-nodes/functions/.gitignore
  rtdb-limit-child-nodes/functions/lib/config.js
  rtdb-limit-child-nodes/functions/lib/index.js
  rtdb-limit-child-nodes/functions/lib/logs.js
  rtdb-limit-child-nodes/functions/package-lock.json
  rtdb-limit-child-nodes/functions/package.json
  rtdb-limit-child-nodes/functions/tsconfig.json
Labels: cla: yes

#809 chore(firestore-translate-text): added prepare script
  firestore-translate-text/functions/.gitignore
  firestore-translate-text/functions/lib/config.js
  firestore-translate-text/functions/lib/index.js
  firestore-translate-text/functions/lib/logs/index.js
  firestore-translate-text/functions/lib/logs/messages.js
  firestore-translate-text/functions/lib/validators.js
  firestore-translate-text/functions/package-lock.json
  firestore-translate-text/functions/package.json
  firestore-translate-text/functions/src/index.ts
  firestore-translate-text/functions/tsconfig.json
Labels: cla: yes

#808 chore(firestore-shorten-urls-bitly): added prepare script
  firestore-shorten-urls-bitly/.gitignore
  firestore-shorten-urls-bitly/functions/lib/abstract-shortener.js
  firestore-shorten-urls-bitly/functions/lib/config.js
  firestore-shorten-urls-bitly/functions/lib/index.js
  firestore-shorten-urls-bitly/functions/lib/logs.js
  firestore-shorten-urls-bitly/functions/package-lock.json
  firestore-shorten-urls-bitly/functions/package.json
  firestore-shorten-urls-bitly/functions/src/abstract-shortener.ts
  firestore-shorten-urls-bitly/functions/tsconfig.json
Labels: cla: yes

#811 chore(firestore-send-email):added prepare script
  firestore-send-email/functions/.gitignore
  firestore-send-email/functions/lib/config.js
  firestore-send-email/functions/lib/index.js
  firestore-send-email/functions/lib/logs.js
  firestore-send-email/functions/lib/templates.js
  firestore-send-email/functions/lib/types.js
  firestore-send-email/functions/package-lock.json
  firestore-send-email/functions/package.json
  firestore-send-email/functions/tsconfig.json
Labels: cla: yes

#798 chore(auth-mailchimp-sync): updated to node14, added prepare script
  auth-mailchimp-sync/extension.yaml
  auth-mailchimp-sync/functions/.gitignore
  auth-mailchimp-sync/functions/lib/config.js
  auth-mailchimp-sync/functions/lib/index.js
  auth-mailchimp-sync/functions/lib/logs.js
  auth-mailchimp-sync/functions/package-lock.json
  auth-mailchimp-sync/functions/package.json
  auth-mailchimp-sync/functions/tsconfig.json
Labels: cla: yes

#813 chore(firestore-bigquery-export):added prepare script
  firestore-bigquery-export/functions/.gitignore
  firestore-bigquery-export/functions/lib/logs.js
  firestore-bigquery-export/functions/lib/util.js
  firestore-bigquery-export/functions/package-lock.json
  firestore-bigquery-export/functions/package.json
  firestore-bigquery-export/functions/tsconfig.json
Labels: cla: yes

#817 chore(firestore-counter): added prepare script
  firestore-counter/functions/.gitignore
  firestore-counter/functions/lib/aggregator.js
  firestore-counter/functions/lib/common.js
  firestore-counter/functions/lib/controller.js
  firestore-counter/functions/lib/index.js
  firestore-counter/functions/lib/planner.js
  firestore-counter/functions/lib/worker.js
  firestore-counter/functions/package-lock.json
  firestore-counter/functions/package.json
  firestore-counter/functions/src/worker.ts
  firestore-counter/functions/tsconfig.json
  storage-resize-images/functions/package-lock.json
Labels: cla: yes

#806 chore(firestore-bigquery-export): updated wildcard collection documentation
  firestore-bigquery-export/README.md
Labels: cla: yes

#800 chore(delete-user-data): added prepare script
  delete-user-data/functions/.gitignore
  delete-user-data/functions/lib/config.js
  delete-user-data/functions/lib/helpers.js
  delete-user-data/functions/lib/index.js
  delete-user-data/functions/lib/logs.js
  delete-user-data/functions/package-lock.json
  delete-user-data/functions/package.json
  delete-user-data/functions/tsconfig.json
Labels: cla: yes

#551 [firestore-bigquery-export/@fs-bq-import-collection] enhance error outputs when specified `--non-interactive` with invalid arguments
  firestore-bigquery-export/scripts/import/package-lock.json
  firestore-bigquery-export/scripts/import/src/index.ts
Labels: good first issue, cla: yes

#710 fix(firestore-send-email): added logging for invalid email messages, documentation updated with firestore example
  firestore-send-email/README.md
  firestore-send-email/functions/lib/index.js
  firestore-send-email/functions/lib/logs.js
  firestore-send-email/functions/src/index.ts
  firestore-send-email/functions/src/logs.ts
Labels: cla: yes, in-review

#779 fix(*): generate correct `package-lock.json` files after `lerna bootstrap`
  delete-user-data/test-data/package-lock.json
  firestore-bigquery-export/firestore-bigquery-change-tracker/package-lock.json
  firestore-bigquery-export/functions/package-lock.json
  firestore-bigquery-export/functions/package.json
  firestore-bigquery-export/scripts/gen-schema-view/package-lock.json
  firestore-bigquery-export/scripts/import/package-lock.json
  firestore-translate-text/functions/package-lock.json
  package.json
Labels: cla: yes

#906 fix(firestore-bigquery-export): updated type check on partitioned date fields
  firestore-bigquery-export/firestore-bigquery-change-tracker/package-lock.json
  firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/e2e.test.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/partitioning.test.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/fixtures/queries.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/partitioning.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/types.ts
  firestore-bigquery-export/functions/package-lock.json
  firestore-bigquery-export/functions/package.json
Labels: cla: yes
