Repository firebase/extensions, pull requests merged in 2022-11, with the labels that each got.

#1287 docs: updated firestore bundle builder links
  docs/firestore-bundle-builder/get-started.md
Labels: documentation

#1217 fix(firestore-bigquery-export): updating table metadata too often
  firestore-bigquery-export/firestore-bigquery-change-tracker/jest.config.js
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/checkUpdates.test.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/e2e.test.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/stresstest.test.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/checkUpdates.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/partitioning.ts
Labels: in-review

#1297 November release
  .github/workflows/validate.yml
  .husky/.gitignore
  .husky/pre-commit
  README.md
  delete-user-data/test-data/package-lock.json
  docs/delete-user-data/get-started.md
  docs/firestore-bundle-builder/api-reference.md
  docs/firestore-bundle-builder/get-started.md
  docs/firestore-bundle-builder/media/admin-ui.png
  firestore-bigquery-export/CHANGELOG.md
  firestore-bigquery-export/extension.yaml
  firestore-bigquery-export/firestore-bigquery-change-tracker/jest.config.js
  firestore-bigquery-export/firestore-bigquery-change-tracker/package-lock.json
  firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/checkUpdates.test.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/e2e.test.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/snapshot.test.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/stresstest.test.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/fixtures/changeTracker.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/fixtures/sql/generateSnapshotStresstestTable.sql
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/fixtures/sql/latestConsistentSnapshot.sql
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/fixtures/sql/latestConsistentSnapshot.txt
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/fixtures/sql/latestConsistentSnapshotNoGroupBy.sql
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/checkUpdates.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/partitioning.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/schema.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/snapshot.ts
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/tracker.ts
  firestore-bigquery-export/functions/package-lock.json
  firestore-bigquery-export/functions/package.json
  firestore-bigquery-export/functions/src/config.ts
  firestore-bigquery-export/functions/src/index.ts
  firestore-bigquery-export/scripts/gen-schema-view/src/snapshot.ts
  firestore-bigquery-export/scripts/import/package-lock.json
  firestore-bigquery-export/scripts/import/package.json
  firestore-bigquery-export/scripts/import/src/config.ts
  firestore-bigquery-export/scripts/import/src/index.ts
  firestore-bigquery-export/scripts/import/src/run.ts
  firestore-bigquery-export/scripts/import/src/types.ts
  firestore-send-email/CHANGELOG.md
  firestore-send-email/PREINSTALL.md
  firestore-send-email/README.md
  firestore-send-email/extension.yaml
  firestore-send-email/functions/package-lock.json
  package-lock.json
  package.json
  storage-resize-images/CHANGELOG.md
  storage-resize-images/PREINSTALL.md
  storage-resize-images/README.md
  storage-resize-images/extension.yaml
  storage-resize-images/functions/package-lock.json
  storage-resize-images/functions/src/index.ts
  storage-resize-images/functions/src/resize-image.ts
  storage-resize-images/functions/src/util.ts
Labels: cla: yes, kokoro:run

#1322 fix(firestore-bigquery-export): improve table update checks
  firestore-bigquery-export/extension.yaml
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
  firestore-bigquery-export/functions/package-lock.json
  firestore-bigquery-export/scripts/import/package-lock.json
Labels: in-progress
