Repository firebase/extensions, pull requests merged in 2023-02, with the labels that each got.

#1412 [firestore-counter]: e2e testing
  _emulator/extensions/firestore-counter.env.local
  _emulator/firebase.json
  firestore-counter/functions/__tests__/e2e.test.ts
  firestore-counter/functions/__tests__/test-client.ts
  firestore-counter/functions/__tests__/test.types.d.ts
  firestore-counter/functions/__tests__/tsconfig.json
  firestore-counter/functions/jest.config.js
  firestore-counter/functions/package-lock.json
  firestore-counter/functions/package.json
  firestore-counter/functions/src/controller.ts
Labels: in-review

#1395 fix(storage-resize-images): support backfill task in custom region
  storage-resize-images/functions/__tests__/__snapshots__/config.test.ts.snap
  storage-resize-images/functions/src/config.ts
  storage-resize-images/functions/src/index.ts
Labels: type: feature request

#1411 fix(firestore-bigquery-export): fixed partition data sync
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/partitioning.ts
Labels: in-review

#1410 feat(firestore-send-email): add TTL support
  _emulator/extensions/firestore-send-email.env.local
  _emulator/extensions/firestore-send-email.secret.local
  firestore-send-email/extension.yaml
  firestore-send-email/functions/__tests__/config.test.ts
  firestore-send-email/functions/__tests__/e2e.test.ts
  firestore-send-email/functions/src/config.ts
  firestore-send-email/functions/src/index.ts
  firestore-send-email/functions/src/types.ts
Labels: in-review

#1416 [storage-resize-images] Always use posix paths when writing to storage
  storage-resize-images/functions/src/resize-image.ts
Labels: in-review

#1435 @invertase/fix release tests
  firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/bigquery/schema.test.ts
  firestore-counter/functions/package.json
  storage-resize-images/functions/__tests__/e2e.test.ts
Labels: in-review

#1421 feat(*): upgrade extensions to the latest firebase-admin sdk
  _emulator/functions/package-lock.json
  _emulator/functions/package.json
  auth-mailchimp-sync/functions/jest.config.js
  auth-mailchimp-sync/functions/package-lock.json
  auth-mailchimp-sync/functions/package.json
  delete-user-data/functions/jest.config.js
  delete-user-data/functions/package-lock.json
  delete-user-data/functions/package.json
  delete-user-data/functions/tsconfig.json
  delete-user-data/test-data/package-lock.json
  delete-user-data/test-data/package.json
  firestore-bigquery-export/firestore-bigquery-change-tracker/package-lock.json
  firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
  firestore-bigquery-export/firestore-bigquery-change-tracker/tsconfig.json
  firestore-bigquery-export/functions/package-lock.json
  firestore-bigquery-export/functions/package.json
  firestore-bigquery-export/scripts/gen-schema-view/package-lock.json
  firestore-bigquery-export/scripts/gen-schema-view/package.json
  firestore-bigquery-export/scripts/import/package-lock.json
  firestore-bigquery-export/scripts/import/package.json
  firestore-bigquery-export/scripts/import/src/types.ts
  firestore-counter/POSTINSTALL.md
  firestore-counter/clients/node/package.json
  firestore-counter/functions/jest.config.js
  firestore-counter/functions/package-lock.json
  firestore-counter/functions/package.json
  firestore-counter/functions/src/controller.ts
  firestore-counter/functions/src/worker.ts
  firestore-counter/functions/test/worker.ts
  firestore-counter/stress_test/bin/package.json
  firestore-counter/stress_test/functions/package.json
  firestore-send-email/functions/__tests__/e2e.test.ts
  firestore-send-email/functions/jest.config.js
  firestore-send-email/functions/package-lock.json
  firestore-send-email/functions/package.json
  firestore-send-email/functions/src/index.ts
  firestore-send-email/functions/src/logs.ts
  firestore-send-email/functions/src/templates.ts
  firestore-send-email/functions/src/types.ts
  firestore-shorten-urls-bitly/functions/package-lock.json
  firestore-shorten-urls-bitly/functions/package.json
  firestore-translate-text/functions/package-lock.json
  firestore-translate-text/functions/package.json
  package-lock.json
  rtdb-limit-child-nodes/functions/package-lock.json
  rtdb-limit-child-nodes/functions/package.json
  rtdb-limit-child-nodes/functions/src/index.ts
  storage-resize-images/functions/__tests__/e2e.test.ts
  storage-resize-images/functions/package-lock.json
  storage-resize-images/functions/package.json
Labels: in-review

#1455 fix(firestore-bigquery-export): add checks for existing firebase apps
  firestore-bigquery-export/scripts/gen-schema-view/src/index.ts
  firestore-bigquery-export/scripts/import/src/index.ts
Labels: in-review, extension: firestore-bigquery-export

#1463 fix(firestore-send-email): added template check when no message exists
  firestore-send-email/functions/__tests__/e2e.test.ts
  firestore-send-email/functions/src/index.ts
Labels: in-review
