Repository firebase/extensions, pull requests merged in 2023-03, with the labels that each got.

#1474 fix(firestore-bigquery-export): Added support for callable transform functions
  firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
Labels: type: feature request

#1415 Update import script docs to warn about duplication on multiple runs
  firestore-bigquery-export/guides/IMPORT_EXISTING_DOCUMENTS.md
Labels: documentation, in-review

#1376 Replace deprecated String.prototype.substr()
  firestore-counter/clients/node/index.js
  firestore-counter/clients/web/src/index.ts
Labels: in-review

#1496 feat(storage-resize-images): handle jfif file extensions correctly
  storage-resize-images/functions/__tests__/e2e.test.ts
  storage-resize-images/functions/__tests__/test-img.jfif
  storage-resize-images/functions/src/resize-image.ts
Labels: in-review

#1473 fix(delete-user-data): improve search deletions
  delete-user-data/functions/__tests__/helpers.test.ts
  delete-user-data/functions/__tests__/runBatchPubSubDeletions.test.ts
  delete-user-data/functions/__tests__/search.test.ts
  delete-user-data/functions/jest.config.js
  delete-user-data/functions/src/helpers.ts
  delete-user-data/functions/src/index.ts
  delete-user-data/functions/src/logs.ts
  delete-user-data/functions/src/types.ts
Labels: in-review

#1507 docs(delete-user-data): make docs more clear on custom function
  delete-user-data/README.md
  delete-user-data/extension.yaml
  package.json
Labels: in-review
